workspace(name = "tensorflow_gnn")

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

# TF archive
load("@tensorflow_gnn//package:tfdep.bzl", "tf_setup")
tf_setup()

http_archive(
  name = "rules_proto",
  sha256 = "<sha256>",
  strip_prefix = "rules_proto-5.3.0-21.7",
  urls = [
    "https://github.com/bazelbuild/rules_proto/archive/refs/tags/5.3.0-21.7.tar.gz",
  ]
)

http_archive(
  name = "rules_python",
  sha256 = "<sha256>",
  strip_prefix = "rules_python-0.26.0",
  url = "https://github.com/bazelbuild/rules_python/releases/download/0.26.0/rules_python-0.26.0.tar.gz",
)